sudo: false
language: generic
services:
  - docker
env:
  - PERL_VERSION="5.30"
  - PERL_VERSION="5.28"
  - PERL_VERSION="5.24"
  - PERL_VERSION="5.20"
  - PERL_VERSION="5.16"
addons:
  apt:
    packages:
      - libxml2-utils
      - libxml-libxml-perl
      - libxml-libxslt-perl
script:
- xmllint --noout df.*.xml symbols.xml
- docker run --rm -v $PWD:/xml -v ./travis/run-codegen.bash:/run-codegen.bash -v ./codegen-out.txt:/out.txt perl:${PERL_VERSION}-slim bash /run-codegen.bash
- if grep -i error codegen-out.txt; then false; else true; fi
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#dfhack"
    on_success: change
    on_failure: always
