sudo: false
language: generic
services:
  - docker
env:
  - PERL_VERSION="5.24"
  - PERL_VERSION="5.22"
  - PERL_VERSION="5.20"
  - PERL_VERSION="5.18"
  - PERL_VERSION="5.16"
addons:
  apt:
    packages:
      - libxml2-utils
      - libxml-libxml-perl
      - libxml-libxslt-perl
script:
- xmllint --noout df.*.xml symbols.xml
- set -o pipefail; docker run --rm -v $PWD:/xml perl:${PERL_VERSION}-slim perl /xml/codegen.pl | tee codegen-out.txt
- if grep -i error codegen-out.txt; then false; else true; fi
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#dfhack"
    on_success: change
    on_failure: always
